version: "3"
services:

  outline:
    image: outlinewiki/outline:0.64.4                             
    env_file: docker.env
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis
    env_file: docker.env
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    env_file: docker.env
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: outline         # outline
      POSTGRES_PASSWORD: 6q2DT2s67c # 6q2DT2s67c
      POSTGRES_DB: outline             # outline
    healthcheck:
      test: ["CMD", "postgres_isready -U outline"]
      interval: 30s
      timeout: 20s
      retries: 3

  storage:
    image: minio/minio
    env_file: docker.env
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001"' 
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MINIO_ROOT_USER:     vai5VeixeShif2chshaeRe7e     
      MINIO_ROOT_PASSWORD: UJaa9Tiexal5eiB0oang8ooT 
    volumes:
      - storage-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  https-portal:
    image: steveltn/https-portal
    env_file: docker.env
    ports:
      - '80:80'
      - '443:443'
    links:
      - outline
      - storage
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    environment:
      DOMAINS: wiki.xpdev.tech -> http://outline:3000 
      STAGE: staging
      WEBSOCKET: true
      CLIENT_MAX_BODY_SIZE: 100M
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  https-portal-data:
  storage-data:
  database-data:
