# Warning! Don't edit this file. It's generated by terraform
[defaults]
remote_user = ${remote_user}
host_key_checking = False

[ssh_connection]
ssh_args=-i ${private_key_path} -o ControlMaster=auto -o ControlPersist=60s
