# Warning! Don't edit this file. It's generated by terraform
%{ for group_name, host_list in hosts ~}
[${group_name}]
%{ for host in host_list ~}
${host.hostname} ansible_host=${host.ip}
%{ endfor ~}

%{ endfor ~}

