---
- name: Check if docker installed
  shell: |
    docker
  register: results
  failed_when:
    - "'not found' in results.stdout"

- name: Install docker-compose from official github repo
  get_url:
    url: https://github.com/docker/compose/releases/download/"{{ docker_compose_version }}"/docker-compose-linux-x86_64 
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Copy env
  ansible.builtin.copy:
    src: docker.env
    dest: /home/outline/docker.env
    owner: root
    mode: '777'

- name: Copy compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /home/outline/docker-compose.yml
    owner: root
    mode: '777'

- name: Copy setup-db script
  ansible.builtin.copy:
    src: setup-outline-db.sh
    dest: /home/outline/setup-outline-db.sh
    owner: root
    mode: '755'

- block:

  - name: Create db
    shell: 
      cmd: |
        docker-compose run --rm outline yarn sequelize db:create --env=production-ssl-disabled
      chdir: /home/outline
    register: output

  - debug:
      var: output

  - name: Migrate db
    shell: 
      cmd: |
        docker-compose run --rm outline yarn sequelize db:migrate --env=production-ssl-disabled
      chdir: /home/outline
    register: output

  - debug:
      var: output

  when: 
    - "{{ apply_migrations }}" == "true"

- name: Start outline
  shell: 
    cmd: |
      docker-compose down || true
      docker-compose up -d
    chdir: /home/outline
  register: output

- debug:
    var: output
